name: "Publicar Easy Presenter"

# Esto le dice a GitHub que solo construya los instaladores 
# cuando crees una etiqueta (tag) que empiece con "v", por ejemplo: "v1.0.0"
on:
  push:
    tags:
      - 'v*'

jobs:
  crear-instaladores:
    strategy:
      fail-fast: false
      matrix:
        # Aquí definimos las 3 computadoras virtuales
        platform: [windows-latest, ubuntu-22.04]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      # Esta parte instala las librerías necesarias de Linux Mint/Ubuntu
      - name: Instalar dependencias de Linux
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav
          chmod 666 src-tauri/*.db
          chmod +x src-tauri/libpdfium.so

      - name: Instalar dependencias del Frontend (React)
        run: npm install

      # Esto compila la App y la sube a la sección de Releases
      - name: Construir y Publicar Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # Toma la versión de tu tauri.conf.json
          releaseName: 'Easy Presenter v__VERSION__'
          releaseBody: 'Nuevos instaladores listos para descargar.'
          releaseDraft: false
          prerelease: false